version: "3"
services:
  monitoring:
    build: 
      context: .
      dockerfile: Dockerfile
    image: parachain-node-monitoring  
    container_name: parachain-node-monitoring
    ports:
      - 9090:9090
    environment:
      email_secret: "${{ secrets.EMAIL_SECRET }}"
    links:
      - webhook
    networks:
      - default

  webhook:
    image: benjojo/alertmanager-discord:latest
    container_name: discord-webhook-trigger
    environment: 
      DISCORD_WEBHOOK: $"{{ secrets.DISCORD_WEBHOOK }}" #release channel webhook
    ports:
      - "9094:9094"
    networks:
      - default
