global:
  scrape_interval: 15s
  evaluation_interval: 15s 
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - ["parachain-node-monitoring:9093"]
rule_files:
  - alert.rules.yml
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["parachain-node-monitoring:9090"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["parachain-node-monitoring:9100"]
  - job_name: "substrate_node"
    static_configs:
      - targets: ["parachain-node-monitoring:9615"]
  - job_name: "isnotexist"
      - targets: ["parachain-node-monitoring:8080"]
