name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main                                         
jobs: 
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@master
      - env:
          VERSION: "latest"
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/marocchino/setup-ecs-cli/v1/entrypoint.sh)"
