name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main                                         
jobs: 
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@master
      - uses: marocchino/setup-ecs-cli@v1
        with:
          version: "v1.18.0"
