name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: parachain-node-monitoring           # set this to your Amazon ECR repository name
  ECS_SERVICE: monitoring                 # set this to your Amazon ECS service name
  ECS_CLUSTER: parachain-cluster                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION:  ./task-definition.json # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: parachain-node-monitor-container           # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to EC2
        run: |
              sudo yum install ecs-init && sudo start ecs
              ecs-cli configure --cluster dct-cluster --region us-east-1 --default-launch-type EC2 --config-name dct-cluster
              # ecs-cli configure profile --access-key <access_key_id> --secret-key <secret_key_id> --profile-name dct-cluster
              # ecs-cli up --vpc vpc-00b3c7c1da63df46b --keypair <rsa-key> --capability-iam --size 2 --instance-type t2.micro --cluster-config dct-cluster --subnets subnet-00c7785fc7e459c18,subnet-054d388c83867a6fc
              # ecs-cli compose up --create-log-groups --cluster-config dct-cluster 
